[[
  {
    "name": "symfony.messenger.consume",
    "service": "symfony_messenger_test",
    "resource": "async -> App\\Message\\LuckyNumberNotification",
    "trace_id": 0,
    "span_id": 1,
    "parent_id": 2084276157927715233,
    "type": "queue",
    "error": 1,
    "meta": {
      "_dd.code_origin.frames.0.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php",
      "_dd.code_origin.frames.0.line": "143",
      "_dd.code_origin.frames.0.method": "handleMessage",
      "_dd.code_origin.frames.0.type": "Symfony\\Component\\Messenger\\Worker",
      "_dd.code_origin.frames.1.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php",
      "_dd.code_origin.frames.1.line": "76",
      "_dd.code_origin.frames.1.method": "run",
      "_dd.code_origin.frames.1.type": "Symfony\\Component\\Messenger\\Worker",
      "_dd.code_origin.frames.2.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php",
      "_dd.code_origin.frames.2.line": "150",
      "_dd.code_origin.frames.2.method": "execute",
      "_dd.code_origin.frames.2.type": "Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand",
      "_dd.code_origin.frames.3.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php",
      "_dd.code_origin.frames.3.line": "264",
      "_dd.code_origin.frames.3.method": "run",
      "_dd.code_origin.frames.3.type": "Symfony\\Component\\Console\\Command\\Command",
      "_dd.code_origin.frames.4.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php",
      "_dd.code_origin.frames.4.line": "972",
      "_dd.code_origin.frames.4.method": "doRunCommand",
      "_dd.code_origin.frames.4.type": "Symfony\\Component\\Console\\Application",
      "_dd.code_origin.frames.5.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php",
      "_dd.code_origin.frames.5.line": "80",
      "_dd.code_origin.frames.5.method": "doRunCommand",
      "_dd.code_origin.frames.5.type": "Symfony\\Bundle\\FrameworkBundle\\Console\\Application",
      "_dd.code_origin.frames.6.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php",
      "_dd.code_origin.frames.6.line": "217",
      "_dd.code_origin.frames.6.method": "doRun",
      "_dd.code_origin.frames.6.type": "Symfony\\Component\\Console\\Application",
      "_dd.code_origin.frames.7.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php",
      "_dd.code_origin.frames.7.line": "67",
      "_dd.code_origin.frames.7.method": "doRun",
      "_dd.code_origin.frames.7.type": "Symfony\\Bundle\\FrameworkBundle\\Console\\Application",
      "_dd.code_origin.type": "exit",
      "_dd.p.dm": "0",
      "_dd.p.tid": "686e4ae600000000",
      "component": "symfonymessenger",
      "error.message": "Uncaught Symfony\\Component\\Messenger\\Exception\\UnrecoverableMessageHandlingException: Number is out of bounds in {path}/tests/Frameworks/Symfony/Version_6_2/src/MessageHandler/LuckyNumberNotificationHandler.php:15",
      "error.stack": "#0 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(157): App\\MessageHandler\\LuckyNumberNotificationHandler->__invoke()\n#1 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(96): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->callHandler()\n#2 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#3 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#4 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#5 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#6 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#7 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#8 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#9 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#10 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#11 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#12 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#13 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#14 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#15 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#16 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#17 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#18 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#19 {path}/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#20 {main}\n\nNext Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129\nStack trace:\n#0 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 {path}/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
      "error.type": "Symfony\\Component\\Messenger\\Exception\\UnrecoverableMessageHandlingException",
      "messaging.destination": "async",
      "messaging.destination_kind": "queue",
      "messaging.message_id": "2",
      "messaging.operation": "receive",
      "messaging.symfony.bus": "messenger.bus.default",
      "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
      "messaging.system": "symfony",
      "runtime-id": "2c16b8d8-34d0-47f0-b0e3-f87694a8559b",
      "span.kind": "consumer"
    },
    "metrics": {
      "_sampling_priority_v1": 1
    }
  },
     {
       "name": "symfony.Symfony\\Component\\Messenger\\Event\\WorkerMessageReceivedEvent",
       "service": "symfony_messenger_test",
       "resource": "symfony.Symfony\\Component\\Messenger\\Event\\WorkerMessageReceivedEvent",
       "trace_id": 0,
       "span_id": 2,
       "parent_id": 1,
       "type": "queue",
       "meta": {
         "component": "symfony"
       }
     },
     {
       "name": "symfony.messenger.dispatch",
       "service": "symfony_messenger_test",
       "resource": "async -> App\\Message\\LuckyNumberNotification",
       "trace_id": 0,
       "span_id": 3,
       "parent_id": 1,
       "type": "queue",
       "error": 1,
       "meta": {
         "component": "symfonymessenger",
         "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
         "error.stack": "#0 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 {path}/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
         "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
         "messaging.destination": "async",
         "messaging.destination_kind": "queue",
         "messaging.message_id": "2",
         "messaging.operation": "process",
         "messaging.symfony.bus": "messenger.bus.default",
         "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
         "messaging.system": "symfony"
       },
       "metrics": {
         "messaging.symfony.stamps.Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineReceivedStamp": 1,
         "messaging.symfony.stamps.Symfony\\Component\\Messenger\\Stamp\\AckStamp": 1,
         "messaging.symfony.stamps.Symfony\\Component\\Messenger\\Stamp\\BusNameStamp": 1,
         "messaging.symfony.stamps.Symfony\\Component\\Messenger\\Stamp\\ConsumedByWorkerStamp": 1,
         "messaging.symfony.stamps.Symfony\\Component\\Messenger\\Stamp\\ReceivedStamp": 1,
         "messaging.symfony.stamps.Symfony\\Component\\Messenger\\Stamp\\SerializerStamp": 2,
         "messaging.symfony.stamps.Symfony\\Component\\Messenger\\Stamp\\TransportMessageIdStamp": 1
       }
     },
        {
          "name": "symfony.messenger.middleware",
          "service": "symfony_messenger_test",
          "resource": "Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware",
          "trace_id": 0,
          "span_id": 7,
          "parent_id": 3,
          "type": "queue",
          "error": 1,
          "meta": {
            "component": "symfonymessenger",
            "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
            "error.stack": "#0 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 {path}/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
            "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
            "messaging.destination": "async",
            "messaging.destination_kind": "queue",
            "messaging.message_id": "2",
            "messaging.operation": "process",
            "messaging.symfony.bus": "messenger.bus.default",
            "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
            "messaging.system": "symfony"
          }
        },
           {
             "name": "symfony.messenger.middleware",
             "service": "symfony_messenger_test",
             "resource": "Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware",
             "trace_id": 0,
             "span_id": 8,
             "parent_id": 7,
             "type": "queue",
             "error": 1,
             "meta": {
               "component": "symfonymessenger",
               "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
               "error.stack": "#0 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 {path}/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
               "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
               "messaging.destination": "async",
               "messaging.destination_kind": "queue",
               "messaging.message_id": "2",
               "messaging.operation": "process",
               "messaging.symfony.bus": "messenger.bus.default",
               "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
               "messaging.system": "symfony"
             }
           },
              {
                "name": "symfony.messenger.middleware",
                "service": "symfony_messenger_test",
                "resource": "Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware",
                "trace_id": 0,
                "span_id": 9,
                "parent_id": 8,
                "type": "queue",
                "error": 1,
                "meta": {
                  "component": "symfonymessenger",
                  "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
                  "error.stack": "#0 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 {path}/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
                  "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
                  "messaging.destination": "async",
                  "messaging.destination_kind": "queue",
                  "messaging.message_id": "2",
                  "messaging.operation": "process",
                  "messaging.symfony.bus": "messenger.bus.default",
                  "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
                  "messaging.system": "symfony"
                }
              },
                 {
                   "name": "symfony.messenger.middleware",
                   "service": "symfony_messenger_test",
                   "resource": "Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware",
                   "trace_id": 0,
                   "span_id": 10,
                   "parent_id": 9,
                   "type": "queue",
                   "error": 1,
                   "meta": {
                     "component": "symfonymessenger",
                     "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
                     "error.stack": "#0 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 {path}/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
                     "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
                     "messaging.destination": "async",
                     "messaging.destination_kind": "queue",
                     "messaging.message_id": "2",
                     "messaging.operation": "process",
                     "messaging.symfony.bus": "messenger.bus.default",
                     "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
                     "messaging.system": "symfony"
                   }
                 },
                    {
                      "name": "symfony.messenger.middleware",
                      "service": "symfony_messenger_test",
                      "resource": "Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware",
                      "trace_id": 0,
                      "span_id": 11,
                      "parent_id": 10,
                      "type": "queue",
                      "error": 1,
                      "meta": {
                        "component": "symfonymessenger",
                        "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
                        "error.stack": "#0 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 {path}/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
                        "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
                        "messaging.destination": "async",
                        "messaging.destination_kind": "queue",
                        "messaging.message_id": "2",
                        "messaging.operation": "process",
                        "messaging.symfony.bus": "messenger.bus.default",
                        "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
                        "messaging.system": "symfony"
                      }
                    },
                       {
                         "name": "symfony.messenger.middleware",
                         "service": "symfony_messenger_test",
                         "resource": "Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware",
                         "trace_id": 0,
                         "span_id": 12,
                         "parent_id": 11,
                         "type": "queue",
                         "error": 1,
                         "meta": {
                           "component": "symfonymessenger",
                           "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
                           "error.stack": "#0 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 {path}/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
                           "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
                           "messaging.destination": "async",
                           "messaging.destination_kind": "queue",
                           "messaging.message_id": "2",
                           "messaging.operation": "process",
                           "messaging.symfony.bus": "messenger.bus.default",
                           "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
                           "messaging.system": "symfony"
                         }
                       },
                          {
                            "name": "symfony.messenger.middleware",
                            "service": "symfony_messenger_test",
                            "resource": "Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware",
                            "trace_id": 0,
                            "span_id": 13,
                            "parent_id": 12,
                            "type": "queue",
                            "error": 1,
                            "meta": {
                              "component": "symfonymessenger",
                              "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\HandlerFailedException: Handling \"App\\Message\\LuckyNumberNotification\" failed: Number is out of bounds in {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:129",
                              "error.stack": "#0 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#1 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#2 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#3 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#4 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#5 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#6 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#7 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#8 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#9 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#10 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#11 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#12 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#13 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#14 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#15 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#16 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#17 {path}/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#18 {main}",
                              "error.type": "Symfony\\Component\\Messenger\\Exception\\HandlerFailedException",
                              "messaging.destination": "async",
                              "messaging.destination_kind": "queue",
                              "messaging.message_id": "2",
                              "messaging.operation": "process",
                              "messaging.symfony.bus": "messenger.bus.default",
                              "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
                              "messaging.system": "symfony"
                            }
                          },
                             {
                               "name": "symfony.messenger.handle",
                               "service": "symfony_messenger_test",
                               "resource": "App\\MessageHandler\\LuckyNumberNotificationHandler",
                               "trace_id": 0,
                               "span_id": 14,
                               "parent_id": 13,
                               "type": "queue",
                               "error": 1,
                               "meta": {
                                 "component": "symfonymessenger",
                                 "error.message": "Thrown Symfony\\Component\\Messenger\\Exception\\UnrecoverableMessageHandlingException: Number is out of bounds in {path}/tests/Frameworks/Symfony/Version_6_2/src/MessageHandler/LuckyNumberNotificationHandler.php:15",
                                 "error.stack": "#0 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(157): App\\MessageHandler\\LuckyNumberNotificationHandler->__invoke()\n#1 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php(96): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->callHandler()\n#2 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(77): Symfony\\Component\\Messenger\\Middleware\\HandleMessageMiddleware->handle()\n#3 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\\Component\\Messenger\\Middleware\\SendMessageMiddleware->handle()\n#4 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\\Component\\Messenger\\Middleware\\FailedMessageProcessingMiddleware->handle()\n#5 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\\Component\\Messenger\\Middleware\\DispatchAfterCurrentBusMiddleware->handle()\n#6 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\\Component\\Messenger\\Middleware\\RejectRedeliveredMessageMiddleware->handle()\n#7 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Middleware/TraceableMiddleware.php(40): Symfony\\Component\\Messenger\\Middleware\\AddBusNameStampMiddleware->handle()\n#8 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/MessageBus.php(70): Symfony\\Component\\Messenger\\Middleware\\TraceableMiddleware->handle()\n#9 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/RoutableMessageBus.php(54): Symfony\\Component\\Messenger\\MessageBus->dispatch()\n#10 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(161): Symfony\\Component\\Messenger\\RoutableMessageBus->dispatch()\n#11 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Worker.php(110): Symfony\\Component\\Messenger\\Worker->handleMessage()\n#12 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\\Component\\Messenger\\Worker->run()\n#13 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Command/Command.php(312): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute()\n#14 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(1040): Symfony\\Component\\Console\\Command\\Command->run()\n#15 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\\Component\\Console\\Application->doRunCommand()\n#16 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(314): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()\n#17 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\\Component\\Console\\Application->doRun()\n#18 {path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/console/Application.php(168): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()\n#19 {path}/tests/Frameworks/Symfony/Version_6_2/bin/console(43): Symfony\\Component\\Console\\Application->run()\n#20 {main}",
                                 "error.type": "Symfony\\Component\\Messenger\\Exception\\UnrecoverableMessageHandlingException",
                                 "messaging.destination_kind": "queue",
                                 "messaging.operation": "process",
                                 "messaging.symfony.message": "App\\Message\\LuckyNumberNotification",
                                 "messaging.system": "symfony"
                               }
                             },
     {
       "name": "symfony.Symfony\\Component\\Messenger\\Event\\WorkerMessageFailedEvent",
       "service": "symfony_messenger_test",
       "resource": "symfony.Symfony\\Component\\Messenger\\Event\\WorkerMessageFailedEvent",
       "trace_id": 0,
       "span_id": 4,
       "parent_id": 1,
       "type": "queue",
       "meta": {
         "component": "symfony"
       }
     },
     {
       "name": "PDO.prepare",
       "service": "pdo",
       "resource": "UPDATE messenger_messages SET delivered_at = ? WHERE id = ?",
       "trace_id": 0,
       "span_id": 5,
       "parent_id": 1,
       "type": "sql",
       "meta": {
         "_dd.base_service": "symfony_messenger_test",
         "_dd.code_origin.frames.0.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/doctrine/dbal/src/Driver/PDO/Connection.php",
         "_dd.code_origin.frames.0.line": "56",
         "_dd.code_origin.frames.0.method": "prepare",
         "_dd.code_origin.frames.0.type": "Doctrine\\DBAL\\Driver\\PDO\\Connection",
         "_dd.code_origin.frames.1.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/doctrine/dbal/src/Driver/Middleware/AbstractConnectionMiddleware.php",
         "_dd.code_origin.frames.1.line": "26",
         "_dd.code_origin.frames.1.method": "prepare",
         "_dd.code_origin.frames.1.type": "Doctrine\\DBAL\\Driver\\Middleware\\AbstractConnectionMiddleware",
         "_dd.code_origin.frames.2.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/doctrine/dbal/src/Logging/Connection.php",
         "_dd.code_origin.frames.2.line": "30",
         "_dd.code_origin.frames.2.method": "prepare",
         "_dd.code_origin.frames.2.type": "Doctrine\\DBAL\\Logging\\Connection",
         "_dd.code_origin.frames.3.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/doctrine/dbal/src/Driver/Middleware/AbstractConnectionMiddleware.php",
         "_dd.code_origin.frames.3.line": "26",
         "_dd.code_origin.frames.3.method": "prepare",
         "_dd.code_origin.frames.3.type": "Doctrine\\DBAL\\Driver\\Middleware\\AbstractConnectionMiddleware",
         "_dd.code_origin.frames.4.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/doctrine-bridge/Middleware/Debug/Connection.php",
         "_dd.code_origin.frames.4.line": "38",
         "_dd.code_origin.frames.4.method": "prepare",
         "_dd.code_origin.frames.4.type": "Symfony\\Bridge\\Doctrine\\Middleware\\Debug\\Connection",
         "_dd.code_origin.frames.5.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/doctrine/dbal/src/Connection.php",
         "_dd.code_origin.frames.5.line": "1193",
         "_dd.code_origin.frames.5.method": "executeStatement",
         "_dd.code_origin.frames.5.type": "Doctrine\\DBAL\\Connection",
         "_dd.code_origin.frames.6.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/doctrine/dbal/src/Connection.php",
         "_dd.code_origin.frames.6.line": "763",
         "_dd.code_origin.frames.6.method": "update",
         "_dd.code_origin.frames.6.type": "Doctrine\\DBAL\\Connection",
         "_dd.code_origin.frames.7.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/doctrine-messenger/Transport/Connection.php",
         "_dd.code_origin.frames.7.line": "259",
         "_dd.code_origin.frames.7.method": "reject",
         "_dd.code_origin.frames.7.type": "Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\Connection",
         "_dd.code_origin.type": "exit",
         "component": "pdo",
         "db.charset": "utf8mb4",
         "db.engine": "mysql",
         "db.name": "symfony62",
         "db.system": "mysql",
         "db.type": "mysql",
         "db.user": "test",
         "out.host": "mysql-integration",
         "out.port": "3306",
         "span.kind": "client"
       }
     },
     {
       "name": "PDOStatement.execute",
       "service": "pdo",
       "resource": "UPDATE messenger_messages SET delivered_at = ? WHERE id = ?",
       "trace_id": 0,
       "span_id": 6,
       "parent_id": 1,
       "type": "sql",
       "meta": {
         "_dd.base_service": "symfony_messenger_test",
         "_dd.code_origin.frames.0.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/doctrine/dbal/src/Driver/PDO/Statement.php",
         "_dd.code_origin.frames.0.line": "118",
         "_dd.code_origin.frames.0.method": "execute",
         "_dd.code_origin.frames.0.type": "Doctrine\\DBAL\\Driver\\PDO\\Statement",
         "_dd.code_origin.frames.1.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php",
         "_dd.code_origin.frames.1.line": "67",
         "_dd.code_origin.frames.1.method": "execute",
         "_dd.code_origin.frames.1.type": "Doctrine\\DBAL\\Driver\\Middleware\\AbstractStatementMiddleware",
         "_dd.code_origin.frames.2.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/doctrine/dbal/src/Logging/Statement.php",
         "_dd.code_origin.frames.2.line": "90",
         "_dd.code_origin.frames.2.method": "execute",
         "_dd.code_origin.frames.2.type": "Doctrine\\DBAL\\Logging\\Statement",
         "_dd.code_origin.frames.3.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php",
         "_dd.code_origin.frames.3.line": "67",
         "_dd.code_origin.frames.3.method": "execute",
         "_dd.code_origin.frames.3.type": "Doctrine\\DBAL\\Driver\\Middleware\\AbstractStatementMiddleware",
         "_dd.code_origin.frames.4.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/doctrine-bridge/Middleware/Debug/Statement.php",
         "_dd.code_origin.frames.4.line": "55",
         "_dd.code_origin.frames.4.method": "execute",
         "_dd.code_origin.frames.4.type": "Symfony\\Bridge\\Doctrine\\Middleware\\Debug\\Statement",
         "_dd.code_origin.frames.5.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/doctrine/dbal/src/Connection.php",
         "_dd.code_origin.frames.5.line": "1193",
         "_dd.code_origin.frames.5.method": "executeStatement",
         "_dd.code_origin.frames.5.type": "Doctrine\\DBAL\\Connection",
         "_dd.code_origin.frames.6.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/doctrine/dbal/src/Connection.php",
         "_dd.code_origin.frames.6.line": "763",
         "_dd.code_origin.frames.6.method": "update",
         "_dd.code_origin.frames.6.type": "Doctrine\\DBAL\\Connection",
         "_dd.code_origin.frames.7.file": "{path}/tests/Frameworks/Symfony/Version_6_2/vendor/symfony/doctrine-messenger/Transport/Connection.php",
         "_dd.code_origin.frames.7.line": "259",
         "_dd.code_origin.frames.7.method": "reject",
         "_dd.code_origin.frames.7.type": "Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\Connection",
         "_dd.code_origin.type": "exit",
         "component": "pdo",
         "db.charset": "utf8mb4",
         "db.engine": "mysql",
         "db.name": "symfony62",
         "db.system": "mysql",
         "db.type": "mysql",
         "db.user": "test",
         "out.host": "mysql-integration",
         "out.port": "3306",
         "span.kind": "client"
       },
       "metrics": {
         "db.row_count": 1
       }
     }]]
